tekton: add delta-spark-publish task and use custom delta-spark 4.1.0-spark410
delta-spark 4.0.1 (compiled against Spark 4.0.x) causes NoSuchMethodError:
LogKey.$init$ on Spark 4.1.0 because LogKey changed from Scala trait to Java
interface. Build delta-spark from upstream master branch which has Spark 4.1
shims (DeltaLogKey abstract class instead of trait).

Published to Nexus as io.delta:delta-spark_4.1_2.13:4.1.0-spark410

Co-Authored-By: Craft Agent <agents-noreply@craft.do>